#!/usr/bin/env python3
"""
biorag_calibration_figures_v1.py — the key on one page, with its support values
===============================================================================

A phylogeny is legible because the topology and the confidence in it are in the
same picture: you read the branching order and the support at each node together,
and you never have to open a table to know which parts to believe. A key deserves
the same treatment. These two sheets are meant to be read that way.

  fig_key_report.png        the key drawn as a tree, every terminal coloured by how
                            often the key actually reaches that species when the
                            specimen's own record is withheld — support values, in
                            the phylogenetic sense — beside the accuracy you can
                            expect by series size, how well each novelty rule
                            recognises a species the key has never seen, and the
                            recommendation with its warnings.

  fig_character_report.png  which characters carry the key and how cleanly each one
                            separates, and, for descriptive words scored by a model,
                            how often the same image gets the same word twice.

Both are generated by the `calibrate` pipeline step; run directly to redraw.

  python biorag_calibration_figures_v1.py --calibration "$M/calibration" \\
      --key_tree "$M/key/key_tree.json" [--reliability "$M/.../character_reliability.tsv"]
"""

import argparse
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt                                    # noqa: E402
import numpy as np                                                 # noqa: E402
import pandas as pd                                                # noqa: E402
from matplotlib.patches import Rectangle                           # noqa: E402

VERSION = "1.0"
GOOD, FAIR, POOR, GREY = "#2e7d32", "#f9a825", "#c62828", "#9e9e9e"


def acc_colour(a):
    if a is None or (isinstance(a, float) and np.isnan(a)):
        return GREY
    return GOOD if a >= 0.75 else (FAIR if a >= 0.5 else POOR)


# ══════════════════════════════════════════════════════════════════════════════
# the key as a tree
# ══════════════════════════════════════════════════════════════════════════════
def ladder(tree):
    """Walk the key and return terminals in reading order with their depth, plus the
    couplet that produced each one. A dichotomous key is a rooted binary tree; this
    lays it out the way a phylogeny is laid out, deepest path running down the page."""
    by_no = {c["number"]: c for c in tree["couplets"]}
    terminals, nodes = [], []
    seen = set()

    def walk(n, depth):
        if n in seen or n not in by_no:
            return
        seen.add(n)
        c = by_no[n]
        ch = (c.get("characters") or [{}])[0]
        nodes.append({"number": n, "depth": depth, "label": ch.get("label", "—"),
                      "threshold": ch.get("threshold"), "unit": ch.get("unit", ""),
                      "perfect": bool(ch.get("perfect_separation")),
                      "accuracy": ch.get("balanced_accuracy")})
        for side in ("A", "B"):
            g = c.get(f"{side}_goto")
            if isinstance(g, int):
                walk(g, depth + 1)
            elif g:
                terminals.append({"species": g, "depth": depth + 1, "from": n, "side": side})
    walk(tree["couplets"][0]["number"], 0)
    return nodes, terminals


def draw_key(ax, tree, per_species, support=None):
    nodes, terminals = ladder(tree)
    if not terminals:
        ax.axis("off")
        return
    y = {t["species"]: i for i, t in enumerate(sorted(
        terminals, key=lambda t: (t["depth"], t["species"])))}
    maxd = max(t["depth"] for t in terminals) or 1
    node_y = {}
    for n in sorted({t["from"] for t in terminals}):
        kids = [y[t["species"]] for t in terminals if t["from"] == n]
        node_y[n] = float(np.mean(kids)) if kids else 0.0
    depth_of = {n["number"]: n["depth"] for n in nodes}

    for t in terminals:                                  # branch to each terminal
        x0 = depth_of.get(t["from"], 0)
        yy = y[t["species"]]
        a = per_species.get(t["species"], {}).get("accuracy")
        ax.plot([x0, maxd + 0.15], [node_y.get(t["from"], yy), yy],
                color="#607d8b", lw=0.9, zorder=1, solid_capstyle="round")
        n_sp = per_species.get(t["species"], {}).get("n", 0)
        ax.scatter([maxd + 0.15], [yy], s=42, color=acc_colour(a), zorder=3,
                   edgecolor="white", linewidth=0.6)
        txt = f"  {t['species']}"
        if a is not None and not (isinstance(a, float) and np.isnan(a)):
            txt += f"   {100 * a:.0f}%  (n={n_sp})"
        else:
            txt += f"   —  (n={n_sp})"
        ax.text(maxd + 0.28, yy, txt, va="center", fontsize=7.4,
                color="#212121" if n_sp >= 3 else "#8d6e63")

    last_lab = [-99.0]
    used = {}                                            # couplets drawn on one spot: stack their support labels
    for n in nodes:                                      # the couplet characters
        if n["number"] not in node_y:
            continue
        ax.scatter([n["depth"]], [node_y[n["number"]]], marker="s", s=14,
                   color="#37474f" if n["perfect"] else "#90a4ae", zorder=3)
        sv = (support or {}).get(n["number"])
        if sv is not None:                               # jackknife support, as on a phylogeny's nodes
            rec, rout, nr = sv
            txt = f"{100 * rec:.0f}" + (f" · {100 * rout:.0f}" if rout == rout and nr >= 3 else " · –")
            spot = (n["depth"], round(node_y[n["number"]], 1))
            k = used.get(spot, 0)
            used[spot] = k + 1
            dy = -0.42 - 0.40 * k if k % 2 == 0 else 0.46 + 0.40 * (k - 1)
            ax.text(n["depth"] + 0.07, node_y[n["number"]] + dy, f"{n['number']}: " + txt, fontsize=4.9, ha="left", va="center",
                    color="#b71c1c" if (rout == rout and nr >= 5 and rout < 0.75) else "#1a237e", zorder=4)
        if n["perfect"] and abs(node_y[n["number"]] - last_lab[0]) > 1.6:
            ax.text(n["depth"] - 0.14, node_y[n["number"]], n["label"][:22], fontsize=5.2,
                    ha="right", va="center", color="#546e7a")
            last_lab[0] = node_y[n["number"]]

    ax.set_xlim(-0.6, maxd + 3.4)
    ax.set_ylim(-1.5, len(y) + 0.5)
    ax.invert_yaxis()
    ax.axis("off")
    ax.set_title("The key, and how often it reaches each species\n"
                 "terminal colour = leave-one-specimen-out accuracy; squares = couplets "
                 "(dark = perfect separation)"
                 + ("\nat each couplet, its number, then the delete-one jackknife: % of rebuilt keys that contain it ·\n"
                    "% of withheld specimens it sent the right way (red below 75%; – fewer than 3 specimens)" if support else ""),
                 fontsize=8.6 if not support else 7.8, loc="left", color="#263238")
    for c, lab in ((GOOD, "≥ 75%"), (FAIR, "50–74%"), (POOR, "< 50%"), (GREY, "not testable")):
        ax.scatter([], [], color=c, s=42, label=lab)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.01), fontsize=6.3, frameon=False,
              ncol=4, title="specimens reaching the right species", title_fontsize=6.3)


# ══════════════════════════════════════════════════════════════════════════════
def panel_by_size(ax, cal):
    by = cal.get("leave_one_specimen_out", {}).get("by_series_size", {})
    if not by:
        ax.axis("off")
        return
    ks = list(by.keys())
    v = [100 * by[k]["accuracy"] for k in ks]
    n = [by[k]["n"] for k in ks]
    ax.bar(ks, v, color=[acc_colour(x / 100) for x in v], width=0.62)
    for i, (a, b) in enumerate(zip(v, n)):
        ax.text(i, a + 2, f"{a:.0f}%\nn={b}", ha="center", fontsize=6.6, color="#37474f")
    ax.set_ylim(0, 112)
    ax.set_ylabel("identified correctly BY THE KEY\n(of specimens that reached a name)", fontsize=7.0)
    ax.set_xlabel("specimens per species in the reference set", fontsize=7.5)
    arm = cal.get("specimen_level_arm", "leave_one_specimen_out")
    ax.set_title("What accuracy to expect, by how much material you have"
                 + ("" if arm == "leave_one_specimen_out" else "  (RESUBSTITUTION — flatters)"),
                 fontsize=8.4, loc="left", color="#263238" if arm == "leave_one_specimen_out" else POOR)
    ax.tick_params(labelsize=7)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)


def panel_rules(ax, cal):
    rows = cal.get("novelty_rules", [])
    if not rows:
        ax.axis("off")
        return
    rec = cal.get("recommended_rule")
    lab = ["\n".join(r["rule"].replace(" leaves the observed range", "\nleaves the range").split("\n"))
           for r in rows]
    yy = np.arange(len(rows))
    det = [100 * (r["unseen_species_flagged"] / max(1, r["of_unseen"])) for r in rows]
    fa = [100 * (r["described_falsely_flagged"] / max(1, r["of_described"])) for r in rows]
    ax.barh(yy - 0.19, det, height=0.36, color="#1565c0", label="unseen species recognised")
    ax.barh(yy + 0.19, fa, height=0.36, color=POOR, label="described species falsely flagged")
    for i, r in enumerate(rows):
        ax.text(det[i] + 1.5, i - 0.19, f"{r['unseen_species_flagged']}/{r['of_unseen']}",
                va="center", fontsize=6.3, color="#1565c0")
        ax.text(fa[i] + 1.5, i + 0.19, f"{r['described_falsely_flagged']}/{r['of_described']}",
                va="center", fontsize=6.3, color=POOR)
        if r["rule"] == rec and r.get("range_definition") == cal.get("recommended_range_definition"):
            ax.add_patch(Rectangle((0, i - 0.46), 118, 0.92, color="#fff8e1", zorder=0))
    ax.set_yticks(yy)
    short = {"observed min/max": "raw range", "95% tolerance interval": "widened"}
    ax.set_yticklabels([f"{r['rule'].replace(', in one specimen', '')}\n"
                        f"[{short.get(r.get('range_definition', ''), '')}]" for r in rows],
                       fontsize=5.9)
    ax.set_xlim(0, 118)
    ax.invert_yaxis()
    ax.set_xlabel("% of species", fontsize=7.5)
    ax.set_title("Every rule, both range definitions\n"
                 "(each species held out in turn; highlighted = recommended here)",
                 fontsize=8.4, loc="left", color="#263238")
    ax.legend(fontsize=6.4, frameon=False, loc="lower right")
    ax.tick_params(labelsize=7)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)


def _nested_point(txt):
    """'19/29 caught, 2/29 false' -> (detection %, false alarm %) or None."""
    import re
    m = re.findall(r"(\d+)\s*/\s*(\d+)", str(txt or ""))
    if len(m) < 2:
        return None
    (c, n1), (f, n2) = m[0], m[1]
    return 100 * int(c) / max(1, int(n1)), 100 * int(f) / max(1, int(n2))


def panel_tradeoff(ax, cal, sweep, matrix_sweep=None):
    """Detection against false alarms, the way a diagnostic test is judged. Points on the
    diagonal carry no information: they flag described and undescribed species alike."""
    ax.plot([0, 100], [0, 100], color="#bdbdbd", lw=0.9, ls="--", zorder=1)
    ax.text(72, 76, "no information", fontsize=6.2, color="#9e9e9e", rotation=38)
    nov = cal.get("instruments", {}).get("novelty", {})
    if matrix_sweep is not None and len(matrix_sweep):
        # upper envelope over rules and thresholds: the most species caught at each false-alarm count
        g = matrix_sweep.groupby("false_alarms")["caught"].max().cummax().reset_index()
        n_u, n_d = matrix_sweep["of_unseen"].iloc[0], matrix_sweep["of_described"].iloc[0]
        ax.step(100 * g["false_alarms"] / n_d, 100 * g["caught"] / n_u, where="post", color="#212121",
                lw=1.8, zorder=4, label="character matrix (every threshold and rule)")
    for name, colour, at in (("character_matrix", "#212121", (2, 89)), ("key", "#d84315", (44, 17))):
        pt = _nested_point(nov.get(name, {}).get("nested_point"))
        if pt:
            ax.scatter([pt[1]], [pt[0]], marker="*", s=130, color=colour, edgecolor="white", lw=0.6, zorder=6)
            ax.annotate(f"{name.replace('_', ' ')}, threshold chosen\nwithout the species tested: "
                        f"{nov[name]['nested_point']}", (pt[1], pt[0]), textcoords="data",
                        xytext=at, fontsize=6.0, color=colour,
                        arrowprops=dict(arrowstyle="-", color=colour, lw=0.6))
    if sweep is not None and len(sweep):
        for rule, g in sweep.groupby("rule"):
            g = g.sort_values("widening_k")
            ax.plot(100 * g["false_alarm"], 100 * g["detection"], marker="o", ms=2.6, lw=1.0,
                    alpha=0.85, label=rule.replace(", in one specimen", ""))
        b = sweep.sort_values(["margin", "detection"], ascending=False).iloc[0]
        ax.scatter([100 * b["false_alarm"]], [100 * b["detection"]], s=120, facecolor="none",
                   edgecolor="#d84315", lw=1.6, zorder=5)
        ax.annotate(f"best here: {b['caught']}/{b['of_unseen']} caught,\n"
                    f"{b['false_alarms']}/{b['of_described']} false alarms",
                    (100 * b["false_alarm"], 100 * b["detection"]),
                    textcoords="offset points", xytext=(8, -22), fontsize=6.4, color="#d84315")
    ax.set_xlim(-2, 102)
    ax.set_ylim(-2, 102)
    ax.set_xlabel("described species wrongly flagged as new (%)", fontsize=7.4)
    ax.set_ylabel("unseen species recognised (%)", fontsize=7.4)
    ax.set_title(("Can the key or the matrix tell you a species is NEW?\n"
                  "(thin lines = key rules swept outwards; stars = honest estimates)"
                  if nov else
                  "Can the key tell you a species is NEW?\n"
                  "(each line = one rule, swept from the raw range outwards)"),
                 fontsize=8.4, loc="left")
    ax.legend(fontsize=5.8, frameon=False, loc="lower right")
    ax.tick_params(labelsize=7)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)


def panel_diagnostic(ax, cal):
    """The reason the flag misfires: a range from n specimens is not the species' range."""
    d = cal.get("range_diagnostic", [])
    if not d:
        ax.axis("off")
        return
    x = np.arange(len(d))
    ax.bar(x - 0.18, [100 * r["observed"] for r in d], width=0.36, color="#5c6bc0",
           label="ordinary conspecific falls outside")
    ax.bar(x + 0.18, [100 * r["expected_from_sample_size"] for r in d], width=0.36,
           color="#bdbdbd", label="expected from sample size alone")
    ax.set_xticks(x)
    ax.set_xticklabels([f"{r['series']}\n(n={r['n']})" for r in d], fontsize=6.8)
    ax.set_ylim(0, 112)
    ax.set_ylabel("% of specimens", fontsize=7.4)
    ax.set_xlabel("specimens per species", fontsize=7.4)
    ax.set_title("Why it misfires: an observed range is not\nthe species' range",
                 fontsize=8.4, loc="left")
    ax.legend(fontsize=6.2, frameon=False, loc="lower left")
    ax.tick_params(labelsize=7)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)


def panel_summary(ax, cal):
    ax.axis("off")
    rs = cal.get("reference_set", {})
    L = [("Reference set", f"{rs.get('species')} species, {rs.get('specimens')} specimens, "
                          f"median {rs.get('median_series')} per species "
                          f"(smallest {rs.get('smallest_series')})")]
    lo = cal.get("leave_one_specimen_out", {})
    ins = cal.get("instruments", {})
    idn, nov = ins.get("identification_leave_one_specimen_out", {}), ins.get("novelty", {})
    if idn.get("key") and idn.get("character_matrix"):
        k, m, ag = idn["key"], idn["character_matrix"], idn.get("key_and_matrix_agree", {})
        L.append(("Naming a specimen, own record withheld",
                  f"character matrix {m['correct']}/{m['of']} ({100 * m['correct'] / m['of']:.0f}%); key "
                  f"{k['correct']}/{k['of']} ({100 * k['correct'] / k['of']:.0f}%; it reached a name for "
                  f"{k['named']}, {100 * k['correct'] / max(1, k['named']):.0f}% of them right)."
                  + (f" Where the two agree ({ag['specimens']} specimens) the name was right "
                     f"{ag['correct']} times." if ag else "")))
        L.append(("Is it a new species? threshold chosen without the species tested",
                  "; ".join(f"{n.replace('_', ' ')}: {nov[n]['nested_point']}" for n in ("character_matrix", "key")
                            if nov.get(n, {}).get("nested_point"))))
        rec_i = str(ins.get("recommended_for_identification", "")).replace("_", " ")
        rec_n = str(ins.get("recommended_for_novelty", "")).replace("_", " ")
        L.append(("Use here", (f"the {rec_i} for both the name and the warning" if rec_i == rec_n else
                               f"the {rec_i} for a name and the {rec_n} for the warning")
                  + "; the key is the printed route a reader can follow, and agreement between the two is "
                    "confirmation."))
    else:
        if lo.get("overall_correct") is not None:
            L.append(("Identification", f"{100 * lo['overall_correct']:.0f}% overall, own record withheld"))
        L.append(("Rule to use here", cal.get("recommended_rule", "—")))
        d, f = cal.get("recommended_rule_detection"), cal.get("recommended_rule_false_alarm")
        if d is not None:
            L.append(("", f"recognises {100 * d:.0f}% of unseen species, "
                          f"falsely flags {100 * (f or 0):.0f}% of described ones"))
    wide = 124 if idn.get("key") and idn.get("character_matrix") else 62   # the box spans two columns
    y = 0.93
    ax.text(0.0, y, "Read this first", fontsize=9, weight="bold", color="#263238",
            transform=ax.transAxes)
    y -= 0.115
    for k, v in L:
        if k:
            ax.text(0.0, y, k, fontsize=7.3, weight="bold", color="#455a64", transform=ax.transAxes)
            y -= 0.072
        for line in _wrap(v, wide):
            ax.text(0.02, y, line, fontsize=7.1, color="#263238", transform=ax.transAxes)
            y -= 0.058
        y -= 0.016
    w = cal.get("warnings", [])
    if w:
        y -= 0.02
        ax.text(0.0, y, "Before quoting any of it", fontsize=7.3, weight="bold", color=POOR,
                transform=ax.transAxes)
        y -= 0.075
        for it in w:
            for j, line in enumerate(_wrap(it, wide - 2)):
                ax.text(0.02, y, ("• " if j == 0 else "   ") + line, fontsize=6.6,
                        color="#6d4c41", transform=ax.transAxes)
                y -= 0.058
            y -= 0.012
    if wide > 62:       # the longer box has no room below: the sentence goes beside the heading
        ax.text(0.16, 0.93, "A flag is a reason to examine the specimens. It is never a determination.",
                fontsize=6.8, style="italic", color="#455a64", transform=ax.transAxes)
        return
    ax.text(0.0, max(y - 0.05, 0.01),
            "A flag is a reason to examine the specimens. It is never a determination.",
            fontsize=6.8, style="italic", color="#455a64", transform=ax.transAxes)


def _wrap(t, n):
    out, cur = [], ""
    for w in str(t).split():
        if len(cur) + len(w) + 1 > n:
            out.append(cur)
            cur = w
        else:
            cur = (cur + " " + w).strip()
    if cur:
        out.append(cur)
    return out or [""]


# ══════════════════════════════════════════════════════════════════════════════
def panel_key_support(ax, support: pd.DataFrame, min_decisions=5):
    """What a key character is worth when the specimen was NOT used to build the key: of the
    leave-one-out decisions taken on that character, the share that sent the specimen to the side
    holding its own species (table written by biorag_graph_support_figure_v1.py)."""
    d = support[support["n_decisions"] >= min_decisions].sort_values("routing_support")
    y = np.arange(len(d))
    ax.barh(y, 100 * d["routing_support"], color="#37474f", height=0.66)
    ax.errorbar(100 * d["routing_support"], y,
                xerr=[100 * (d["routing_support"] - d["ci_low"]), 100 * (d["ci_high"] - d["routing_support"])],
                fmt="none", ecolor="#90a4ae", elinewidth=0.9, capsize=1.5)
    for i, n in enumerate(d["n_decisions"]):
        ax.text(103, i, f"n={n}", va="center", fontsize=5.8, color="#546e7a")
    ax.axvline(50, color=POOR, lw=0.8, ls="--")
    ax.text(50.5, len(d) - 0.35, "chance, two-way step", fontsize=5.8, color=POOR, va="bottom")
    ax.set_yticks(y)
    ax.set_yticklabels([_wrap(t, 44)[0] + ("…" if len(_wrap(t, 44)) > 1 else "") for t in d["label"]],
                       fontsize=6.0)
    ax.set_xlim(0, 116)
    ax.set_xlabel("decisions that sent a withheld specimen towards its own species (%)", fontsize=7.2)
    ax.set_title("What each key character is worth on a specimen the key has not seen\n"
                 f"(leave-one-out; bars = 95% interval; characters with fewer than {min_decisions} decisions omitted)",
                 fontsize=8.2, loc="left")
    ax.tick_params(labelsize=7)
    for s_ in ("top", "right"):
        ax.spines[s_].set_visible(False)


def panel_key_characters(ax, tree):
    rows = []
    for c in tree["couplets"]:
        ch = (c.get("characters") or [{}])[0]
        if not ch.get("label"):
            continue
        rows.append({"label": f"{c['number']}. {ch['label'][:30]}",
                     "acc": ch.get("balanced_accuracy") or 0,
                     "perfect": bool(ch.get("perfect_separation")),
                     "family": ch.get("family", "")})
    if not rows:
        ax.axis("off")
        return
    d = pd.DataFrame(rows).sort_values("acc", ascending=True)      # every couplet, the imperfect ones included
    col = ["#37474f" if p else "#90a4ae" for p in d["perfect"]]
    ax.barh(range(len(d)), 100 * d["acc"], color=col, height=0.66)
    ax.set_yticks(range(len(d)))
    ax.set_yticklabels(d["label"], fontsize=5.6 if len(d) > 24 else 6.2)
    ax.set_xlim(0, 108)
    ax.axvline(100, color=GOOD, lw=0.8, ls=":")
    ax.set_xlabel("balanced accuracy of the split ON THE SPECIMENS THE KEY WAS BUILT FROM (%)", fontsize=7.0)
    ax.set_title("Which characters carry the key — in sample, so near 100% by construction\n"
                 "(dark = the two groups' ranges leave a gap; pale = they separate but touch). For what a\n"
                 "character is worth on an unseen specimen run biorag_graph_support_figure_v1.py",
                 fontsize=7.6, loc="left")
    ax.tick_params(labelsize=7)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)


def panel_families(ax, tree):
    fam = {}
    for c in tree["couplets"]:
        ch = (c.get("characters") or [{}])[0]
        f = ch.get("family")
        if f:
            fam[f] = fam.get(f, 0) + 1
    if not fam:
        ax.axis("off")
        return
    k = sorted(fam, key=fam.get, reverse=True)
    ax.bar(k, [fam[x] for x in k], color="#5c6bc0", width=0.6)
    for i, x in enumerate(k):
        ax.text(i, fam[x] + 0.12, str(fam[x]), ha="center", fontsize=6.8, color="#37474f")
    ax.set_ylabel("couplets", fontsize=7.4)
    ax.set_title("What kind of evidence the key rests on", fontsize=8.4, loc="left")
    ax.tick_params(labelsize=6.6, axis="x", rotation=20)
    ax.tick_params(labelsize=7, axis="y")
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)


def panel_reliability(ax, rel: pd.DataFrame):
    if rel is None or not len(rel):
        ax.axis("off")
        ax.set_title("Descriptive characters: not measured\n"
                     "(run descriptive_states + char_reliability)", fontsize=8.4, loc="left",
                     color=GREY)
        return
    d = rel.sort_values("repeat_exact", ascending=True)
    yy = np.arange(len(d))
    cmap = {"use": GOOD, "use coarse": FAIR, "use_coarse": FAIR, "flag": POOR}
    col = [cmap.get(str(v), GREY) for v in d["verdict"]]
    ax.barh(yy, 100 * d["repeat_exact"], height=0.62, color=col, label="_")
    cz = pd.to_numeric(d.get("repeat_coarse"), errors="coerce")
    ok = cz.notna().values
    ax.scatter(100 * cz[ok], yy[ok], marker="D", s=17, color="#263238", zorder=3,
               label="after merging into bands")
    ax.axvline(80, color="#455a64", lw=0.8, ls="--")
    ax.set_yticks(yy)
    ax.set_yticklabels(d["character"], fontsize=6.6)
    ax.set_xlim(0, 104)
    ax.set_xlabel("same image, same word twice (%)", fontsize=7.4)
    ax.set_title("Descriptive words: can the scorer reproduce itself?\n"
                 "green = use as scored, amber = use as bands, red = set aside here",
                 fontsize=8.4, loc="left")
    ax.legend(fontsize=6.3, frameon=False, loc="lower right")
    ax.tick_params(labelsize=7)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)


def panel_reliability_table(ax, rel: pd.DataFrame, cal):
    ax.axis("off")
    ax.text(0.0, 0.97, "Verdicts carried into the key and the text", fontsize=9,
            weight="bold", color="#263238", transform=ax.transAxes)
    y = 0.86
    groups = [("use as scored", "use", GOOD),
              ("use only as coarse bands", "use_coarse", FAIR),
              ("set aside — not reproducible on these images", "flag", POOR)]
    dc = cal.get("descriptive_characters", {}) if isinstance(cal.get("descriptive_characters"), dict) else {}
    keymap = {"use": "use", "use_coarse": "use_coarse", "flag": "set_aside"}
    for title, k, c in groups:
        names = dc.get(keymap[k]) or []
        if not names and rel is not None and len(rel):
            names = sorted(rel[rel["verdict"].astype(str).str.replace(" ", "_") == k]["character"])
        ax.text(0.0, y, title, fontsize=7.2, weight="bold", color=c, transform=ax.transAxes)
        y -= 0.062
        for line in _wrap(", ".join(names) if names else "none", 58):
            ax.text(0.02, y, line, fontsize=6.9, color="#263238", transform=ax.transAxes)
            y -= 0.055
        y -= 0.025
    y -= 0.02
    ax.text(0.0, y, "Why this matters", fontsize=7.2, weight="bold", color="#455a64",
            transform=ax.transAxes)
    y -= 0.062
    for line in _wrap("A character the scorer cannot reproduce cannot help anyone identify a "
                      "specimen, and stating it in a description spreads the noise further. Set-aside "
                      "characters are kept out of the key and removed from the treatments. Which "
                      "characters survive is a property of this group and these images, not of the "
                      "method — expect a different list in another taxon.", 62):
        ax.text(0.02, y, line, fontsize=6.7, color="#37474f", transform=ax.transAxes)
        y -= 0.055


# ══════════════════════════════════════════════════════════════════════════════
def main():
    ap = argparse.ArgumentParser(description="One-page summaries of the calibration")
    ap.add_argument("--calibration", required=True, help="directory written by biorag_calibrate_v1.py")
    ap.add_argument("--key_tree", required=True)
    ap.add_argument("--reliability", default=None, help="character_reliability.tsv")
    ap.add_argument("--couplet_support", default=None,
                    help="key_couplet_support.tsv from biorag_key_jackknife_support_v1.py; default: "
                         "<calibration>/../key_jackknife_support/, when present")
    ap.add_argument("--key_support", default=None,
                    help="key_character_support.tsv from biorag_graph_support_figure_v1.py (hold-out routing "
                         "support per key character); default: <calibration>/../graph_support/, when present")
    ap.add_argument("--out_dir", default=None)
    a = ap.parse_args()

    cald = Path(a.calibration)
    out = Path(a.out_dir) if a.out_dir else cald
    out.mkdir(parents=True, exist_ok=True)
    cal = json.loads((cald / "calibration.json").read_text())
    tree = json.loads(Path(a.key_tree).read_text())
    per_species = {}
    ps = cald / "per_species.tsv"
    if ps.exists():
        t = pd.read_csv(ps, sep="\t")
        per_species = {r["species"]: {"accuracy": r.get("loo_accuracy"), "n": int(r.get("n", 0))}
                       for _, r in t.iterrows()}
    rel = None
    if a.reliability and Path(a.reliability).exists():
        rel = pd.read_csv(a.reliability, sep="\t")

    # ── sheet 1: the key with its support values ─────────────────────────────
    sweep = None
    sp_f = cald / "novelty_tradeoff.tsv"
    if sp_f.exists():
        sweep = pd.read_csv(sp_f, sep="\t")
    fig = plt.figure(figsize=(17.0, 10.6))
    gs = fig.add_gridspec(4, 3, width_ratios=[1.18, 0.92, 0.92], height_ratios=[1, 1, 1, 1],
                          hspace=0.62, wspace=0.28, left=0.035, right=0.985, top=0.9, bottom=0.055)
    cs_f = Path(a.couplet_support) if a.couplet_support else cald.parent / "key_jackknife_support" / "key_couplet_support.tsv"
    couplet_support = None
    if cs_f.exists():
        cs = pd.read_csv(cs_f, sep="\t")
        couplet_support = {int(r.couplet): (float(r.recovered), float(r.routing_support) if r.routing_support == r.routing_support
                                            else float("nan"), int(r.withheld_specimens_routed)) for r in cs.itertuples()}
    draw_key(fig.add_subplot(gs[:, 0]), tree, per_species, couplet_support)
    panel_by_size(fig.add_subplot(gs[0, 1]), cal)
    panel_diagnostic(fig.add_subplot(gs[0, 2]), cal)
    msw_f = cald / "matrix_tradeoff.tsv"
    msw = pd.read_csv(msw_f, sep="\t") if msw_f.exists() else None
    panel_tradeoff(fig.add_subplot(gs[1:3, 1]), cal, sweep, msw)
    panel_rules(fig.add_subplot(gs[1:3, 2]), cal)
    panel_summary(fig.add_subplot(gs[3, 1:]), cal)
    rs = cal.get("reference_set", {})
    # "everything below" told the reader to look at a position and shouted in
    # capitals; state the claim instead, which is what a caption has to carry
    fig.suptitle(f"Key report — {rs.get('species')} species, {rs.get('specimens')} specimens"
                 f"     |     every cutoff shown was measured on this reference set, "
                 f"not inherited from another study",
                 fontsize=11, x=0.035, ha="left", color="#1a237e")
    f1 = out / "fig_key_report.png"
    fig.savefig(f1, dpi=200)
    fig.savefig(f1.with_suffix(".pdf"))
    plt.close(fig)

    # ── sheet 2: the characters ──────────────────────────────────────────────
    fig = plt.figure(figsize=(14.5, 9.0))
    gs = fig.add_gridspec(2, 2, height_ratios=[1.5, 1], hspace=0.36, wspace=0.28,
                          left=0.17, right=0.98, top=0.88, bottom=0.07)
    sup_f = Path(a.key_support) if a.key_support else cald.parent / "graph_support" / "key_character_support.tsv"
    if sup_f.exists():
        panel_key_support(fig.add_subplot(gs[0, 0]), pd.read_csv(sup_f, sep="\t"))
    else:
        panel_key_characters(fig.add_subplot(gs[0, 0]), tree)
    panel_reliability(fig.add_subplot(gs[0, 1]), rel)
    panel_families(fig.add_subplot(gs[1, 0]), tree)
    panel_reliability_table(fig.add_subplot(gs[1, 1]), rel, cal)
    fig.suptitle("Character report — what the key rests on, and which descriptive categorical characters "
                 "repeated when read again", fontsize=11, x=0.035, ha="left", color="#1a237e")
    f2 = out / "fig_character_report.png"
    fig.savefig(f2, dpi=200)
    fig.savefig(f2.with_suffix(".pdf"))
    plt.close(fig)

    print(f"-> {f1}\n-> {f2}")


if __name__ == "__main__":
    main()
